### ISSUE TITLE
Journal to Journal Comms

### ISSUE THREAD

**Issue by ajrbyers** [revistajs/revista#8]
REVISTA instances should be able to communicate with each other. I think this is important because then it becomes an overlay architecture where "articles" can be pulled as instances across journals and curated into ToCs

**Comment by MartinPaulEve** [comment]
This would be great for "copying" remote articles to a local instance. 
There would have to be some kind of oAuth roundtrip, though, which could 
be a PITA...

On 21/02/16 18:05, Andy Byers wrote:
> REVISTA instances should be able to communicate with each other. I think
> this is important because then it becomes an overlay architecture where
> "articles" can be pulled as instances across journals and curated into ToCs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ajrbyers/revista/issues/8>.
>

-- 
Dr. Martin Paul Eve
Senior Lecturer in Literature, Technology and Publishing
Birkbeck, University of London

T: 0203 073 8420
E: martin.eve@bbk.ac.uk
W: https://www.martineve.com
R: 416, 43 Gordon Square, London, WC1H 0PD

Password [a cultural history]: http://meve.io/password
Pynchon and Philosophy: http://meve.io/pynchonphilo
Open Access and the Humanities: http://meve.io/oahums

Director, Birkbeck Centre for Technology and Publishing
Founder, Open Library of the Humanities (https://www.openlibhums.org)
Chief Editor, Orbit: Writing Around Pynchon (https://www.pynchon.net)
Senior Online Editor, Alluvium, (http://www.alluvium-journal.org)
